### PR TITLE
Types for everything

### PR DESCRIPTION
**Pull request by karlkeefer**
I got rid of all of the `map[string]interface{}` and corresponding assertions.
Also created types for common functions: pointFunc, colorFunc, fractalFunc

The functionality is broadly the same, though the output of `help` is slightly different (utilizes a `String()` method on the fractal struct).

I also changed everything to `color` to match the golang color library name, and moved most of the logic into a `lib` module to scope things a little bit better.

---

probably more commits still to come w/ a new coloring function, but wanted to open this so you could see where it's headed

### CODE REVIEW

**Comment by TheTeaCat** [comment]
Oh my, the removal of `map[string]interface{}`s is truly magnificent. Chef's kiss!

**Comment by TheTeaCat** [comment]
I'm going to merge this in now so I can work on #3.

**Comment by karlkeefer** [comment]
Heads up @TheTeaCat the `go mod` command hardcoded my repo name in a few spots (annoying for any future PRs against upstream :\) - you'll have to change those out if you haven't already.

**Comment by TheTeaCat** [comment]
Oops, thanks! Fixed in 52e4ef5073d5347316831e4149d8f741f544d43d :)

**Pull request merged**
